// APPLICATION DATE FORMAT
export const DATE_FORMAT = 'DD/MM/YYYY';
// APPLICATION BACKGROUND COLOR
export const LIGHT_BACKGROUND_COLOR = '#e6d7ab';
export const DARK_BACKGROUND_COLOR = '#603a18';
export const DEFAULT_OLD_COLOR = '#33b3ab';
export const APPLICATION_TITLE_FONT_FAMILY = "'Open Sans', sans-serif";
// OBJECT STATUS
export const PARTNER_STATUS = {
  PROCESS: 'PROCESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};
export const ORDER_STATUS = {
  INITIALIZATION: 'INITIALIZATION',
  ACCEPTANCE: 'ACCEPTANCE',
  REJECTION: 'REJECTION',
  PREPARATION: 'PREPARATION',
  READINESS: 'READINESS',
  ARRIVAL: 'ARRIVAL',
  RECEPTION: 'RECEPTION',
  WAIT: 'WAIT',
  CANCELLATION: 'CANCELLATION',
  CLOSURE: 'CLOSURE',
};
export const ITEM_STATUS = {
  PROCESS: 'PROCESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};
export const CUSTOMER_STATUS = {
  ACTIVE: 'ACTIVE',
  PASSIVE: 'PASSIVE',
};

export const FCA_ITEM_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVE: 'ARCHIVE',
};

// OPTIONS ARRAY
export const PARTNER_STATUS_ARRAY = [
  'ALL',
  PARTNER_STATUS.PROCESS,
  PARTNER_STATUS.APPROVED,
  PARTNER_STATUS.REJECTED,
];
export const PARTNER_STATUS_OPTIONS = [
  {
    label: PARTNER_STATUS.PROCESS,
    value: PARTNER_STATUS.PROCESS,
  },
  {
    label: PARTNER_STATUS.APPROVED,
    value: PARTNER_STATUS.APPROVED,
  },
  {
    label: PARTNER_STATUS.REJECTED,
    value: PARTNER_STATUS.REJECTED,
  },
];
export const ORDER_STATUS_ARRAY = [
  'ALL',
  ORDER_STATUS.READINESS,
  ORDER_STATUS.ARRIVAL,
  ORDER_STATUS.WAIT,
  ORDER_STATUS.CANCELLATION,
];
// LICENSE TYPE
export const LICENSE_PACKAGE = [
  {
    label: '1 month',
    value: 1,
  },
  {
    label: '3 months',
    value: 3,
  },
  {
    label: '6 months',
    value: 6,
  },
  {
    label: '12 months',
    value: 12,
  },
];
export const ITEM_STATUS_OPTIONS = [
  {
    label: ITEM_STATUS.PROCESS,
    value: ITEM_STATUS.PROCESS,
  },
  {
    label: ITEM_STATUS.APPROVED,
    value: ITEM_STATUS.APPROVED,
  },
  {
    label: ITEM_STATUS.REJECTED,
    value: ITEM_STATUS.REJECTED,
  },
];
