// APPLICATION BACKGROUND COLOR
export const LIGHT_BACKGROUND_COLOR = '#e6d7ab';
export const DARK_BACKGROUND_COLOR = '#603a18';
export const DEFAULT_OLD_COLOR = '#33b3ab';
export const APPLICATION_TITLE_FONT_FAMILY = "'Open Sans', sans-serif";
// OBJECT STATUS
export const PARTNER_STATUS = {
  PROCESS: 'PROCESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};
export const PARTNER_STATUS_ARRAY = [
  PARTNER_STATUS.PROCESS,
  PARTNER_STATUS.APPROVED,
  PARTNER_STATUS.REJECTED,
];
export const PARTNER_STATUS_OPTIONS = [
  {
    label: PARTNER_STATUS.PROCESS,
    value: PARTNER_STATUS.PROCESS,
  },
  {
    label: PARTNER_STATUS.APPROVED,
    value: PARTNER_STATUS.APPROVED,
  },
  {
    label: PARTNER_STATUS.REJECTED,
    value: PARTNER_STATUS.REJECTED,
  },
];
export const ORDER_STATUS = {
  INITIALIZATION: 'INITIALIZATION',
  ACCEPTANCE: 'ACCEPTANCE',
  REJECTION: 'REJECTION',
  PREPARATION: 'PREPARATION',
  READINESS: 'READINESS',
  ARRIVAL: 'ARRIVAL',
  RECEPTION: 'RECEPTION',
  WAIT: 'WAIT',
  CANCELLATION: 'CANCELLATION',
  CLOSURE: 'CLOSURE',
};
export const ORDER_STATUS_ARRAY = [
  ORDER_STATUS.INITIALIZATION,
  ORDER_STATUS.ACCEPTANCE,
  ORDER_STATUS.REJECTION,
  ORDER_STATUS.PREPARATION,
  ORDER_STATUS.READINESS,
  ORDER_STATUS.RECEPTION,
  ORDER_STATUS.ARRIVAL,
  ORDER_STATUS.WAIT,
  ORDER_STATUS.CANCELLATION,
  ORDER_STATUS.CLOSURE,
];
